#!/usr/bin/env python3
"""generate_explorer.py — Generate an interactive HTML dashboard from trace + counter data.

Adapted from the original intra-kernel-profiler's generate_explorer.py for AMD ISA.

Usage:
    python generate_explorer.py --trace trace.json --summary trace_summary.json -o explorer.html
"""

import argparse
import json
import os
import sys


def load_json(path):
    with open(path, "r") as f:
        return json.load(f)


def generate_html(trace_data, summary_data=None, counters_data=None, pcsamp_data=None):
    """Generate a self-contained HTML dashboard."""
    regions = []
    if summary_data and "regions" in summary_data:
        regions = summary_data["regions"]

    html = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>rocprof-intrakernel Explorer</title>
<style>
body { font-family: monospace; margin: 20px; background: #1e1e1e; color: #d4d4d4; }
h1 { color: #569cd6; }
table { border-collapse: collapse; margin: 10px 0; }
th, td { border: 1px solid #555; padding: 4px 8px; text-align: right; }
th { background: #333; color: #9cdcfe; }
tr:hover { background: #2d2d2d; }
.region-name { text-align: left; color: #ce9178; }
.section { margin: 20px 0; }
.section h2 { color: #4ec9b0; }
</style>
</head>
<body>
<h1>rocprof-intrakernel Explorer</h1>
"""

    if regions:
        html += '<div class="section"><h2>Region Summary</h2>\n'
        html += "<table>\n"
        html += "<tr><th>Region</th><th>Name</th><th>Count</th>"
        html += "<th>Mean (ns)</th><th>CV</th><th>Min</th><th>Max</th>"
        html += "<th>P50</th><th>P95</th><th>P99</th></tr>\n"
        for r in regions:
            p = r.get("percentiles", {})
            html += "<tr>"
            html += f'<td>{r["region"]}</td>'
            html += f'<td class="region-name">{r["name"]}</td>'
            html += f'<td>{r["count"]}</td>'
            html += f'<td>{r["mean_dur"]:.1f}</td>'
            cv = r.get("cv_dur")
            html += f'<td>{cv:.3f}</td>' if cv is not None else "<td>-</td>"
            html += f'<td>{r["min_dur"]:.1f}</td>'
            html += f'<td>{r["max_dur"]:.1f}</td>'
            html += f'<td>{p.get("p50", 0):.1f}</td>'
            html += f'<td>{p.get("p95", 0):.1f}</td>'
            html += f'<td>{p.get("p99", 0):.1f}</td>'
            html += "</tr>\n"
        html += "</table></div>\n"

    if counters_data:
        html += '<div class="section"><h2>Hardware Counters</h2>\n'
        html += "<p>Counter data available. Full visualization coming soon.</p>\n"
        html += "</div>\n"

    if pcsamp_data:
        n_samples = len(pcsamp_data.get("samples", []))
        html += '<div class="section"><h2>PC Sampling</h2>\n'
        html += f"<p>{n_samples} samples collected.</p>\n"
        html += "</div>\n"

    html += '<div class="section"><h2>Trace Events</h2>\n'
    events = trace_data.get("traceEvents", [])
    n_events = len([e for e in events if e.get("ph") in ("X", "B", "E", "i")])
    html += f"<p>{n_events} profiling events recorded.</p>\n"
    html += '<p>Load the trace JSON in <a href="https://ui.perfetto.dev" '
    html += 'style="color:#569cd6">Perfetto</a> for interactive visualization.</p>\n'
    html += "</div>\n"

    html += """
<div class="section">
<h2>About</h2>
<p>Generated by <a href="https://github.com/john-hahn/rocprof-intrakernel"
   style="color:#569cd6">rocprof-intrakernel</a></p>
</div>
</body>
</html>"""

    return html


def main():
    parser = argparse.ArgumentParser(description="Generate rocprof-intrakernel explorer HTML")
    parser.add_argument("--trace", required=True, help="Path to trace JSON file")
    parser.add_argument("--summary", help="Path to summary JSON file")
    parser.add_argument("--counters", help="Path to counter collection JSON")
    parser.add_argument("--pcsamp", help="Path to PC sampling JSON")
    parser.add_argument("-o", "--output", default="explorer.html", help="Output HTML path")
    args = parser.parse_args()

    trace_data = load_json(args.trace)
    summary_data = load_json(args.summary) if args.summary else None
    counters_data = load_json(args.counters) if args.counters else None
    pcsamp_data = load_json(args.pcsamp) if args.pcsamp else None

    html = generate_html(trace_data, summary_data, counters_data, pcsamp_data)

    with open(args.output, "w") as f:
        f.write(html)

    print(f"Explorer written to {args.output}")


if __name__ == "__main__":
    main()
